# Generated by Django 4.2.6 on 2023-10-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminCursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='correo_electronico',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='dni',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='descripcion',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='nota',
            field=models.IntegerField(null=True),
        ),
    ]
