# Generated by Django 4.2.6 on 2023-10-24 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminCursos', '0002_alumno_correo_electronico_alumno_dni_alumno_telefono_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandaHoraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('horario_inicio', models.DateTimeField()),
                ('horario_fin', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='banda_horaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminCursos.bandahoraria'),
        ),
    ]
