# Generated by Django 4.2.6 on 2023-11-01 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminCursos', '0003_bandahoraria_curso_banda_horaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('contenido', models.CharField(max_length=300)),
                ('alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminCursos.alumno')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminCursos.curso')),
            ],
        ),
    ]
