# Generated by Django 4.2.6 on 2023-11-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminCursos', '0004_resenia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='curso',
        ),
        migrations.AddField(
            model_name='alumno',
            name='curso',
            field=models.ManyToManyField(null=True, related_name='cursa', to='adminCursos.curso'),
        ),
    ]
